version: "3.7"
services:
  post-cis-gender:
    build: .
    container_name: "postCisGender"
    ports:
      - 5000:5000
    volumes:
      - ./input:/app/input
    networks:
      - stat_network

networks:
  stat_network:
    name: stat_network